apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: guestbook
  description: "A sample multi-tier guestbook app"
  annotations:
    argocd/app-name: guestbook
spec:
  type: service
  lifecycle: experimental
  owner: guest
